osx_image: xcode10.2
os: osx
language: swift
xcode_project: APFancyPagerDemo/APFancyPagerDemo.xcodeproj
xcode_scheme: APFancyPagerDemoUITests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
